name: Test

on:
  push:
    branches:
      - master
      - vaniusrb/issue8
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always
  POSTGRES_PASSWORD: password
  DATABASE_URL: postgres://postgres:password@127.0.0.1/product

jobs:
  test:
    name: Test on ${{ matrix.os }} (using rustc ${{ matrix.rust }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust:
          - nightly
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_POSTGRES_PASSWORD: password
          envkey_DATABASE_URL: postgres://postgres:password@127.0.0.1/product

      # https://github.com/marketplace/actions/docker-compose-action
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yml"
          down-flags: "--volumes"

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: actions-rs/cargo@v1
        with:
          command: test

      # - name: Setup Rust
      #   uses: actions-rs/toolchain@v1
      #   with:
      #     toolchain: ${{ matrix.rust }}
      #     override: true

      # - name: Setup cargo-make
      #   uses: davidB/rust-cargo-make@v1

      # - name: Cargo generate-lockfile
      #   run: cargo generate-lockfile

      # - name: Cargo cache
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       ~/.cargo/bin/
      #       ~/.cargo/registry/index/
      #       ~/.cargo/registry/cache/
      #       ~/.cargo/git/db/
      #       target/
      #     key: ${{ runner.os }}-cargo-${{ matrix.rust }}-${{ hashFiles('**/Cargo.lock') }}

      # - name: Run tests with all features
      #   run: cargo make ci
